export const properties = [
  "Appartement",
  "Villa",
  "Maison",
  "Terrain",
  "Local",
  "Bureau",
  "Depot",
  "Usine",
];
export const locations = [
  "Voir tout",
  "Akouda",
  "Chatt Mariem",
  "Hammam Sousse",
  "Hergla",
  "Kalaa Sghira",
  "Kalaa Kebira",
  "Kantaoui",
  "Khzema",
  "Sahloul",
  "Sousse",
  "Sousse Jawhara",
  "Sousse Riadh",
  "Sidi Abdelhamid",
  "Sidi Bou Ali",
  "Zaouiet Sousse",
];
